neo4jQueries:
  entitiesToCypherQueries:
    - entityPair: "Person"
      query: "MATCH (p:Person {name: $name}) RETURN p"
    - entityPair: "City"
      query: "MATCH (c:City {name: $name}) RETURN c"
